version: "3.9"
services:
 bot:
  build: .
  restart: always
  volumes:
   - '/var/log/discord:/var/log/discord'
  environment:
   - DISCORD_BOTKEY=${DISCORD_BOTKEY}
   - DEBUG_GUILD_ID=${DEBUG_GUILD_ID}
 db:
  image: redis:7.2.1-alpine
  restart: always
  volumes:
   - '/var/opt/tinyrooms:/data'
